"""
generate_data.py

Builds synthetic reference data for the quote automation system:
  - accounts (customers)
  - parts (catalog)
  - account_pricing (the normalized "Master Price List")
  - a simulated ERP export CSV of service orders (data/erp_export.csv)

All data is fictional. Nothing here reflects any real company's actual
accounts, parts, or pricing -- it's structured to demonstrate the workflow,
not to reproduce anyone's real business data.

Usage:
    python scripts/generate_data.py
"""

from __future__ import annotations
import csv
import random
from datetime import date, timedelta
from pathlib import Path

random.seed(7)

ACCOUNTS = [
    ("ACC-1001", "Meridian Property Group",    "Dana Whitfield", "dwhitfield@meridianpg.example",  "Denver",      "CO"),
    ("ACC-1002", "Coastal Retail Holdings",     "Marcus Ibe",     "mibe@coastalretail.example",     "Charleston",  "SC"),
    ("ACC-1003", "Lakeshore Medical Campus",    "Priya Nair",     "pnair@lakeshoremed.example",     "Madison",     "WI"),
    ("ACC-1004", "Union Station Business Park", "Tomas Reyes",    "treyes@unionstationbp.example",  "Kansas City", "MO"),
    ("ACC-1005", "Brightline Logistics",        "Sarah Kowalski", "skowalski@brightlinelog.example","Memphis",     "TN"),
    ("ACC-1006", "Pinehurst School District",   "Wei Chen",       "wchen@pinehurstsd.example",      "Raleigh",     "NC"),
    ("ACC-1007", "Ashford Hotel Group",         "Renee Dubois",   "rdubois@ashfordhg.example",      "New Orleans", "LA"),
    ("ACC-1008", "Northgate Distribution Center","Omar Farouk",   "ofarouk@northgatedc.example",    "Columbus",    "OH"),
    ("ACC-1009", "Cedar Valley Municipal",      "Linda Park",     "lpark@cedarvalleymuni.example",  "Boise",       "ID"),
    ("ACC-1010", "Summit Ridge Apartments",     "Jake Thornton",  "jthornton@summitridge.example",  "Salt Lake City", "UT"),
]

PARTS = [
    ("HW-2201", "Heavy Duty Door Closer",              "Door Hardware", 84.50),
    ("HW-2205", "Commercial Panic Bar Exit Device",    "Door Hardware", 312.00),
    ("HW-2210", "Electromagnetic Door Lock",           "Access Control", 156.75),
    ("HW-2215", "Card Reader - Proximity",             "Access Control", 198.00),
    ("HW-2220", "Keypad Entry Controller",              "Access Control", 143.25),
    ("HW-2230", "Mortise Lock Cylinder",                 "Locks", 42.00),
    ("HW-2235", "Rim Cylinder - Keyed",                   "Locks", 38.50),
    ("HW-2240", "Master Key Core",                         "Locks", 27.75),
    ("HW-2250", "Continuous Hinge - 7ft",                    "Door Hardware", 96.00),
    ("HW-2255", "Door Closer Arm Kit",                        "Door Hardware", 34.25),
    ("HW-2260", "Weatherstrip Seal Kit",                        "Door Hardware", 22.50),
    ("HW-2270", "Wireless Access Control Gateway",                "Access Control", 425.00),
    ("HW-2280", "Emergency Exit Alarm",                             "Access Control", 118.00),
    ("HW-2290", "ADA Compliant Door Operator",                       "Door Hardware", 890.00),
    ("HW-2300", "Threshold Plate - Aluminum",                         "Door Hardware", 41.75),
    ("HW-2310", "Deadbolt - Commercial Grade",                         "Locks", 56.00),
    ("HW-2320", "Push/Pull Bar Set",                                    "Door Hardware", 78.25),
    ("HW-2330", "Door Position Sensor",                                  "Access Control", 29.50),
    ("HW-2340", "Request-to-Exit Motion Sensor",                          "Access Control", 63.75),
    ("HW-2350", "Fire-Rated Door Hinge Set",                               "Door Hardware", 71.00),
]

STATUSES = ["open", "in_progress", "completed"]

DESCRIPTIONS = [
    "Replace exterior door hardware - main entrance",
    "Install access control panel - loading dock",
    "Repair panic bar - east stairwell",
    "Rekey building - management request",
    "Install card readers - 3 doors",
    "Door closer replacement - multiple units",
    "ADA operator install - front lobby",
    "Emergency service - lock malfunction",
    "Scheduled hardware maintenance",
    "New tenant lock change",
]


def generate_accounts(output_dir: Path) -> list[dict]:
    accounts = []
    for i, (num, name, contact, email, city, state) in enumerate(ACCOUNTS, start=1):
        accounts.append({
            "account_id": i,
            "account_number": num,
            "account_name": name,
            "contact_name": contact,
            "contact_email": email,
            "billing_city": city,
            "billing_state": state,
        })
    return accounts


def write_accounts_sql(accounts: list[dict], path: Path) -> None:
    lines = ["-- Auto-generated by scripts/generate_data.py -- do not edit by hand.\n"]
    lines.append("INSERT INTO accounts (account_id, account_number, account_name, contact_name, contact_email, billing_city, billing_state) VALUES")
    values = []
    for a in accounts:
        values.append(
            f"({a['account_id']}, '{a['account_number']}', '{a['account_name']}', "
            f"'{a['contact_name']}', '{a['contact_email']}', '{a['billing_city']}', '{a['billing_state']}')"
        )
    lines.append(",\n".join(values) + ";\n")
    lines.append("SELECT setval('accounts_account_id_seq', (SELECT MAX(account_id) FROM accounts));\n")
    path.write_text("\n".join(lines))


def write_parts_sql(path: Path) -> None:
    lines = ["-- Auto-generated by scripts/generate_data.py -- do not edit by hand.\n"]
    lines.append("INSERT INTO parts (part_number, description, category, list_price) VALUES")
    values = [
        f"('{p[0]}', '{p[1]}', '{p[2]}', {p[3]})"
        for p in PARTS
    ]
    lines.append(",\n".join(values) + ";\n")
    path.write_text("\n".join(lines))


def generate_pricing_sql(accounts: list[dict], path: Path) -> None:
    """Each account gets a negotiated price for a random subset of parts,
    at a discount off list price -- mirrors how the real Master Price List
    had one column of prices per account, not every account carrying
    every part."""
    lines = ["-- Auto-generated by scripts/generate_data.py -- do not edit by hand.\n"]
    lines.append("INSERT INTO account_pricing (account_id, part_number, price, effective_date, expired_date) VALUES")

    values = []
    base_effective = date(2024, 1, 1)

    for account in accounts:
        n_parts = random.randint(10, len(PARTS))
        account_parts = random.sample(PARTS, k=n_parts)
        discount = random.uniform(0.05, 0.20)  # each account negotiates a different discount tier

        for part_number, _, _, list_price in account_parts:
            price = round(list_price * (1 - discount) * random.uniform(0.98, 1.02), 2)
            values.append(
                f"({account['account_id']}, '{part_number}', {price}, '{base_effective}', NULL)"
            )

    lines.append(",\n".join(values) + ";\n")
    path.write_text("\n".join(lines))


def generate_erp_export(accounts: list[dict], n_orders: int, output_path: Path) -> None:
    """Simulates the flat-file export that would come out of the ERP
    in the original workflow. In production, src/erp_sync.py
    would pull this from an actual ERP connection instead of a CSV --
    the sync logic is written to treat this file exactly like that feed."""
    rows = []
    start_date = date(2025, 1, 1)
    order_number = 500100

    for _ in range(n_orders):
        account = random.choice(accounts)
        order_date = start_date + timedelta(days=random.randint(0, 200))
        status = random.choices(STATUSES, weights=[0.15, 0.25, 0.60])[0]

        rows.append({
            "service_order_no": str(order_number),
            "account_number": account["account_number"],
            "order_date": order_date.isoformat(),
            "site_address": f"{random.randint(100, 9999)} {random.choice(['Main St', 'Industrial Pkwy', 'Commerce Dr', 'Broadway', 'Airport Rd'])}, {account['billing_city']}, {account['billing_state']}",
            "description": random.choice(DESCRIPTIONS),
            "erp_status": status,
        })
        order_number += 1

    rows.sort(key=lambda r: r["order_date"])

    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    print(f"Generated {len(rows)} simulated service orders -> {output_path}")


def main():
    project_root = Path(__file__).resolve().parent.parent
    sql_dir = project_root / "sql"
    data_dir = project_root / "data"
    data_dir.mkdir(exist_ok=True)

    accounts = generate_accounts(data_dir)

    write_accounts_sql(accounts, sql_dir / "02_seed_accounts.sql")
    write_parts_sql(sql_dir / "03_seed_parts.sql")
    generate_pricing_sql(accounts, sql_dir / "04_seed_pricing.sql")
    generate_erp_export(accounts, n_orders=120, output_path=data_dir / "erp_export.csv")

    print(f"Generated seed SQL for {len(accounts)} accounts and {len(PARTS)} parts.")
    print("Run in order: 01_schema.sql, 02_seed_accounts.sql, 03_seed_parts.sql, 04_seed_pricing.sql")
    print("Then sync service orders: python src/erp_sync.py")


if __name__ == "__main__":
    main()
