-- Auto-generated by scripts/generate_data.py -- do not edit by hand.

INSERT INTO accounts (account_id, account_number, account_name, contact_name, contact_email, billing_city, billing_state) VALUES
(1, 'ACC-1001', 'Meridian Property Group', 'Dana Whitfield', 'dwhitfield@meridianpg.example', 'Denver', 'CO'),
(2, 'ACC-1002', 'Coastal Retail Holdings', 'Marcus Ibe', 'mibe@coastalretail.example', 'Charleston', 'SC'),
(3, 'ACC-1003', 'Lakeshore Medical Campus', 'Priya Nair', 'pnair@lakeshoremed.example', 'Madison', 'WI'),
(4, 'ACC-1004', 'Union Station Business Park', 'Tomas Reyes', 'treyes@unionstationbp.example', 'Kansas City', 'MO'),
(5, 'ACC-1005', 'Brightline Logistics', 'Sarah Kowalski', 'skowalski@brightlinelog.example', 'Memphis', 'TN'),
(6, 'ACC-1006', 'Pinehurst School District', 'Wei Chen', 'wchen@pinehurstsd.example', 'Raleigh', 'NC'),
(7, 'ACC-1007', 'Ashford Hotel Group', 'Renee Dubois', 'rdubois@ashfordhg.example', 'New Orleans', 'LA'),
(8, 'ACC-1008', 'Northgate Distribution Center', 'Omar Farouk', 'ofarouk@northgatedc.example', 'Columbus', 'OH'),
(9, 'ACC-1009', 'Cedar Valley Municipal', 'Linda Park', 'lpark@cedarvalleymuni.example', 'Boise', 'ID'),
(10, 'ACC-1010', 'Summit Ridge Apartments', 'Jake Thornton', 'jthornton@summitridge.example', 'Salt Lake City', 'UT');

SELECT setval('accounts_account_id_seq', (SELECT MAX(account_id) FROM accounts));
