-- Auto-generated by scripts/generate_data.py -- do not edit by hand.

INSERT INTO parts (part_number, description, category, list_price) VALUES
('HW-2201', 'Heavy Duty Door Closer', 'Door Hardware', 84.5),
('HW-2205', 'Commercial Panic Bar Exit Device', 'Door Hardware', 312.0),
('HW-2210', 'Electromagnetic Door Lock', 'Access Control', 156.75),
('HW-2215', 'Card Reader - Proximity', 'Access Control', 198.0),
('HW-2220', 'Keypad Entry Controller', 'Access Control', 143.25),
('HW-2230', 'Mortise Lock Cylinder', 'Locks', 42.0),
('HW-2235', 'Rim Cylinder - Keyed', 'Locks', 38.5),
('HW-2240', 'Master Key Core', 'Locks', 27.75),
('HW-2250', 'Continuous Hinge - 7ft', 'Door Hardware', 96.0),
('HW-2255', 'Door Closer Arm Kit', 'Door Hardware', 34.25),
('HW-2260', 'Weatherstrip Seal Kit', 'Door Hardware', 22.5),
('HW-2270', 'Wireless Access Control Gateway', 'Access Control', 425.0),
('HW-2280', 'Emergency Exit Alarm', 'Access Control', 118.0),
('HW-2290', 'ADA Compliant Door Operator', 'Door Hardware', 890.0),
('HW-2300', 'Threshold Plate - Aluminum', 'Door Hardware', 41.75),
('HW-2310', 'Deadbolt - Commercial Grade', 'Locks', 56.0),
('HW-2320', 'Push/Pull Bar Set', 'Door Hardware', 78.25),
('HW-2330', 'Door Position Sensor', 'Access Control', 29.5),
('HW-2340', 'Request-to-Exit Motion Sensor', 'Access Control', 63.75),
('HW-2350', 'Fire-Rated Door Hinge Set', 'Door Hardware', 71.0);
